name = "roim-picx"
compatibility_date = "2025-07-12"

# This tells wrangler that this is a Pages project and where the static assets are.
pages_build_output_dir = "public"

# By defining the bindings here, all wrangler commands (including `kv:key put` and `pages dev`)
# will know about your resources.

[[kv_namespaces]]
binding = "XK" # The name of the binding in your code (env.XK)
id = "my-picx" # Placeholder for your production KV namespace ID
preview_id = "my-picx" # Placeholder used for local development

[[r2_buckets]]
binding = "PICX" # The name of the binding in your code (env.PICX)
bucket_name = "medias" # Placeholder for your production R2 bucket name
preview_bucket_name = "medias" # Placeholder used for local development
